// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg0twfZ4Y_-lSDO30ElNcmcs0SvUtPtls',
    appId: '1:838677159608:web:f27f8c2d8d8d2e5483de4d',
    messagingSenderId: '838677159608',
    projectId: 'master-app-otp',
    authDomain: 'master-app-otp.firebaseapp.com',
    storageBucket: 'master-app-otp.appspot.com',
    measurementId: 'G-RBZ2HTJC7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACfJPYg6i7FPEuBUu-dIiqDwJnntMjcgk',
    appId: '1:838677159608:android:01b5e07fc13ee08983de4d',
    messagingSenderId: '838677159608',
    projectId: 'master-app-otp',
    storageBucket: 'master-app-otp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbRv37NPrbYYRM37jXjm2yRsIWtChWZ8',
    appId: '1:838677159608:ios:330317b9420afb6783de4d',
    messagingSenderId: '838677159608',
    projectId: 'master-app-otp',
    storageBucket: 'master-app-otp.appspot.com',
    androidClientId: '838677159608-qc2u59p23n1ofqak0nhfv18hu5oepbtj.apps.googleusercontent.com',
    iosClientId: '838677159608-1gke73v2gthpa6a47uos4pbbrck4p3ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthHandlerDemo',
  );
}
